; Additional Android packaging settings
[/Script/AndroidRuntimeSettings.AndroidRuntimeSettings]
bBuildForES31=False
bSupportsVulkan=True
bSupportsOpenGL3=False
PackageName=com.rok2.thrones
bPackageDataInsideApk=True
bUseExternalFilesDir=False
bEnableGooglePlaySupport=False
bForcePortrait=False
AndroidOrientation=Landscape
MinSDKVersion=26
TargetSDKVersion=34
StoreVersion=1
VersionDisplayName=0.1.0
